import OpenAI from "openai";

const openAI = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export const getGenresForPrompt = async (prompt: string) => {
  const errorMessage = "No response from OpenAI API";

  try {
    const chatResponse = await openAI.chat.completions.create({
      messages: [
        {
          role: "system",
          content:
            "You are an AI that helps users select music genres. Your task is to give a short explanation followed by a list of five relevant genres. Do not include numbers, commas, or any extra text in the genre list—just separate each genre with a line break!",
        },
        {
          role: "user",
          content: `Here is a list of genres: ${genresSeeds} Based on the following prompt, provide five relevant genres at the end: "${prompt}". Provide a brief explanation first, and then list the genres, each on a new line with no additional characters.`,
        },
      ],
      model: "gpt-3.5-turbo",
      max_tokens: 250,
    });

    if (!chatResponse) throw new Error(errorMessage);

    const fullResponse = String(chatResponse.choices[0].message.content);
    const [explanation, genres] = fullResponse.split(":\n\n");

    return {
      explanation,
      genres: genres.split("\n").filter((genre) => genre !== ""),
    };
  } catch (err) {
    console.log(errorMessage);
    return null;
  }
};

const genresSeeds = [
  "acoustic",
  "afrobeat",
  "alt-rock",
  "alternative",
  "ambient",
  "anime",
  "black-metal",
  "bluegrass",
  "blues",
  "bossanova",
  "brazil",
  "breakbeat",
  "british",
  "cantopop",
  "chicago-house",
  "children",
  "chill",
  "classical",
  "club",
  "comedy",
  "country",
  "dance",
  "dancehall",
  "death-metal",
  "deep-house",
  "detroit-techno",
  "disco",
  "disney",
  "drum-and-bass",
  "dub",
  "dubstep",
  "edm",
  "electro",
  "electronic",
  "emo",
  "folk",
  "forro",
  "french",
  "funk",
  "garage",
  "german",
  "gospel",
  "goth",
  "grindcore",
  "groove",
  "grunge",
  "guitar",
  "happy",
  "hard-rock",
  "hardcore",
  "hardstyle",
  "heavy-metal",
  "hip-hop",
  "holidays",
  "honky-tonk",
  "house",
  "idm",
  "indian",
  "indie",
  "indie-pop",
  "industrial",
  "iranian",
  "j-dance",
  "j-idol",
  "j-pop",
  "j-rock",
  "jazz",
  "k-pop",
  "kids",
  "latin",
  "latino",
  "malay",
  "mandopop",
  "metal",
  "metal-misc",
  "metalcore",
  "minimal-techno",
  "movies",
  "mpb",
  "new-age",
  "new-release",
  "opera",
  "pagode",
  "party",
  "philippines-opm",
  "piano",
  "pop",
  "pop-film",
  "post-dubstep",
  "power-pop",
  "progressive-house",
  "psych-rock",
  "punk",
  "punk-rock",
  "r-n-b",
  "rainy-day",
  "reggae",
  "reggaeton",
  "road-trip",
  "rock",
  "rock-n-roll",
  "rockabilly",
  "romance",
  "sad",
  "salsa",
  "samba",
  "sertanejo",
  "show-tunes",
  "singer-songwriter",
  "ska",
  "sleep",
  "songwriter",
  "soul",
  "soundtracks",
  "spanish",
  "study",
  "summer",
  "swedish",
  "synth-pop",
  "tango",
  "techno",
  "trance",
  "trip-hop",
  "turkish",
  "work-out",
  "world-music",
];
